APP_ABI := armeabi armeabi-v7a mips
#APP_ABI += x86
APP_STL := gnustl_static
#APP_STL := stlport_static
APP_CPPFLAGS += -fexceptions
#APP_CFLAGS += -O2
APP_CFLAGS += -O3 # not for x86
#APP_TOOLCHAIN_VERSION := 4.6.3
#APP_USE_CPP0X := true